#!/usr/bin/env python3
"""
Pipeline Step Base — abstract base class for pipeline step handlers.

Eliminates the ~70 lines of boilerplate duplicated across every step
handler in ``run.py`` by encapsulating the common pattern:

  1. Read spec + parse requirements/scenarios
  2. Read prior-step artifacts
  3. Build system/user prompts (subclass provides via prompts.py builders)
  4. Call LLM with retry/timeout (handled by base)
  5. Parse & log usage metadata
  6. Write output file
  7. Return output path
  8. Wrap exceptions as PipelineStepError

Usage::

    class MyStep(PipelineStep):
        step_key = "my-step"
        agent = "Claude"
        description = "My custom step"
        output_filename = "my-step.md"

        def build_prompts(self, session, spec_content, parsed, artifacts):
            from pipeline.prompts import build_xxx_prompt
            return build_xxx_prompt(...)

"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from pipeline.run import PipelineSession, PipelineStepError, _call_llm, _parse_spec

log = logging.getLogger("pipeline.steps")


class PipelineStep:
    """Abstract base for a single pipeline step.

    Subclasses override :meth:`build_prompts` and set class-level
    metadata.  The base class handles LLM invocation, token logging,
    file writing, and error wrapping.
    """

    # ---- Override in subclass -------------------------------------------
    step_key: str = ""
    agent: str = ""
    description: str = ""
    output_filename: str = ""
    # Set to True when the step does NOT call the LLM
    no_llm: bool = False

    # Optional max_tokens override (None = use LLM default)
    max_tokens: Optional[int] = None

    def build_prompts(
        self,
        session: PipelineSession,
        spec_content: str,
        parsed: dict,
        artifacts: dict[str, str],
    ) -> tuple[str, str]:
        """Return ``(system_prompt, user_prompt)``.

        Called by the base class after the spec has been read and
        parsed.  ``artifacts`` maps prior-step keys to their on-disk
        content (already read from the file).
        """
        raise NotImplementedError

    def process_result(
        self,
        session: PipelineSession,
        content: str,
        result: dict,
    ) -> str:
        """Post-process LLM output before writing to file.

        The default implementation prepends a metadata header.
        Override to transform the output (e.g. JSON parsing for
        review steps).  Return the final string to write.
        """
        usage = result.get("usage", {})
        parsed = _parse_spec(session.spec_path)
        requirements = parsed["requirements"]
        scenarios = parsed["scenarios"]
        total_shall = sum(len(r.get("shall_statements", [])) for r in requirements)

        header = (
            f"# {self.description}: {Path(session.spec_path).stem}\n\n"
            f"> Source spec: {session.spec_path}\n"
            f"> Generated by: LLM ({result.get('model', 'unknown')})\n"
            f"> Requirements: {len(requirements)}  |  "
            f"SHALLs: {total_shall}  |  "
            f"Scenarios: {len(scenarios)}\n"
            f"> Tokens: {usage.get('total_tokens', '?')} "
            f"(prompt {usage.get('prompt_tokens', '?')} + "
            f"completion {usage.get('completion_tokens', '?')})\n\n"
        )
        return header + content

    # ---- Template method -------------------------------------------------

    def _read_artifacts(
        self, session: PipelineSession, keys: list[str]
    ) -> dict[str, str]:
        """Read the content of prior-step artifacts from disk."""
        contents: dict[str, str] = {}
        for key in keys:
            if key in session.artifacts:
                p = Path(session.artifacts[key])
                if p.exists():
                    contents[key] = p.read_text()
        return contents

    def __call__(self, session: PipelineSession) -> str:
        """Execute the step (called by the pipeline orchestrator)."""
        import time as _time

        _t0 = _time.perf_counter()
        try:
            log.info("Running %s: %s", self.agent, self.description)
            print(f"  {self._icon()} [{self.agent}] {self.description}...")

            # --- Read spec ---
            spec_path = Path(session.spec_path)
            spec_content = (
                spec_path.read_text()
                if spec_path.exists()
                else "(spec file not found)"
            )
            parsed = _parse_spec(session.spec_path)

            # --- Read prior-step artifact content ---
            artifact_keys = self._artifact_keys()
            artifacts = self._read_artifacts(session, artifact_keys)

            # --- Build prompts & call LLM (or skip for non-LLM steps) ---
            if self.no_llm:
                result = self._run_without_llm(
                    session, spec_content, parsed, artifacts
                )
            else:
                system_prompt, user_prompt = self.build_prompts(
                    session, spec_content, parsed, artifacts
                )
                kwargs = {}
                if self.max_tokens is not None:
                    kwargs["max_tokens"] = self.max_tokens
                try:
                    result = _call_llm(session, system_prompt, user_prompt, **kwargs)
                except Exception as e:
                    log.error("LLM call failed during %s: %s", self.step_key, e)
                    raise PipelineStepError(
                        f"{self.description} LLM call failed: {e}\n"
                        f"Spec: {session.spec_path}"
                    )

                content = result["content"]
                usage = result.get("usage", {})
                log.info(
                    "LLM returned %d tokens (prompt=%s, completion=%s) [%s]",
                    usage.get("total_tokens", "?"),
                    usage.get("prompt_tokens", "?"),
                    usage.get("completion_tokens", "?"),
                    self.step_key,
                )

                # Accumulate token usage on session
                if hasattr(session, "token_usage_total"):
                    session.token_usage_total += usage.get("total_tokens", 0)
                    session.token_usage_steps.append({
                        "step": self.step_key,
                        "usage": usage,
                    })

                # --- Post-process & write ---
                full_output = self.process_result(session, content, result)

            out_path = session.session_dir / self.output_filename
            try:
                out_path.write_text(
                    result if self.no_llm else full_output
                )
            except OSError as e:
                log.error("Cannot write %s: %s", self.output_filename, e)
                raise PipelineStepError(
                    f"Cannot write {self.output_filename}: {e}"
                )

            print(
                f"  ✅ [{self.agent}] {self.description} "
                f"generated at {out_path}"
            )
            _elapsed = _time.perf_counter() - _t0
            log.info("%s saved to %s (%.3fs)", self.step_key, out_path, _elapsed)
            return str(out_path)

        except PipelineStepError:
            _elapsed = _time.perf_counter() - _t0
            log.info("Step %s FAILED after %.3fs", self.step_key, _elapsed)
            raise
        except Exception as e:
            _elapsed = _time.perf_counter() - _t0
            log.error("%s failed after %.3fs: %s", self.step_key, _elapsed, e)
            raise PipelineStepError(f"{self.description} failed: {e}")

    # ---- Hooks for subclasses --------------------------------------------

    def _icon(self) -> str:
        """Return the emoji icon for this step."""
        return "🔄"

    def _artifact_keys(self) -> list[str]:
        """Return keys of prior-step artifacts to read.

        The base class returns an empty list.  Override in steps that
        depend on earlier outputs.
        """
        return []

    def _run_without_llm(
        self,
        session: PipelineSession,
        spec_content: str,
        parsed: dict,
        artifacts: dict[str, str],
    ) -> str:
        """Called when ``no_llm = True``.

        Return the content to write to the output file.
        """
        raise NotImplementedError


# ---------------------------------------------------------------------------
# Concrete step implementations
# ---------------------------------------------------------------------------


class SuperAnalysisStep(PipelineStep):
    """Step 1: 小明 — S.U.P.E.R analysis powered by real LLM."""

    step_key = "super-analysis"
    agent = "小明"
    description = "S.U.P.E.R 启动分析"
    output_filename = "startup-analysis.md"

    def build_prompts(self, session, spec_content, parsed, artifacts):
        from pipeline.prompts import build_super_analysis_prompt

        requirements = parsed["requirements"]
        scenarios = parsed["scenarios"]
        return build_super_analysis_prompt(
            spec_content=spec_content,
            spec_name=Path(session.spec_path).name,
            requirements=requirements,
            scenarios=scenarios,
        )

    def _icon(self):
        return "📊"


class PrdStep(PipelineStep):
    """Step 2: Hermes — AI-powered PRD generation from spec."""

    step_key = "prd"
    agent = "Hermes"
    description = "产品需求分析"
    output_filename = "prd.md"

    def _artifact_keys(self):
        return ["super-analysis"]

    def build_prompts(self, session, spec_content, parsed, artifacts):
        from pipeline.prompts import build_prd_prompt

        requirements = parsed["requirements"]
        scenarios = parsed["scenarios"]
        return build_prd_prompt(
            spec_content=spec_content,
            spec_name=Path(session.spec_path).name,
            requirements=requirements,
            scenarios=scenarios,
            super_analysis_content=artifacts.get("super-analysis", ""),
        )

    def _icon(self):
        return "🔮"


class ArchitectureStep(PipelineStep):
    """Step 4: Claude — AI-powered architecture design."""

    step_key = "architecture"
    agent = "Claude"
    description = "架构设计"
    output_filename = "architecture.md"
    max_tokens = 4096

    def build_prompts(self, session, spec_content, parsed, artifacts):
        from pipeline.prompts import build_architecture_prompt
        import os

        project_dir = Path(os.environ.get("OSH_HOME", ".")).resolve()
        src_dir = project_dir / "src"

        directories: list[str] = []
        source_files: list[str] = []
        tech_stack: set[str] = set()
        src_tree_lines: list[str] = []

        if src_dir.exists():
            for root, dirs, files in os.walk(src_dir):
                dirs[:] = [
                    d
                    for d in dirs
                    if not d.startswith(".") and d != "__pycache__"
                ]
                rel_dir = Path(root).relative_to(project_dir)
                directories.append(str(rel_dir))
                indent = (
                    "  " * (len(Path(rel_dir).parts) - 1)
                    if len(Path(rel_dir).parts) > 1
                    else ""
                )
                src_tree_lines.append(f"{indent}{Path(rel_dir).name}/")
                for f in sorted(files):
                    if f.endswith(
                        (
                            ".py", ".sh", ".html", ".js", ".css", ".ts",
                            ".go", ".rs", ".json", ".toml", ".yaml", ".yml", ".md",
                        )
                    ):
                        source_files.append(str(Path(rel_dir) / f))
                        src_tree_lines.append(f"{indent}  {f}")
                        ext = Path(f).suffix
                        if ext == ".py":
                            tech_stack.add("Python")
                        elif ext == ".go":
                            tech_stack.add("Go")
                        elif ext == ".rs":
                            tech_stack.add("Rust")
                        elif ext in (".html", ".js", ".css", ".ts"):
                            tech_stack.add("Web (HTML/JS/CSS)")
                        elif ext == ".sh":
                            tech_stack.add("Shell")

        key_file_snippets: list[str] = []
        for sf in sorted(source_files)[:15]:
            fpath = project_dir / sf
            if fpath.exists() and fpath.stat().st_size < 10000:
                try:
                    content = fpath.read_text()[:2000]
                    key_file_snippets.append(f"### {sf}\n```\n{content}\n```")
                except Exception as e:
                    log.warning("Could not read source file %s: %s", sf, e)
                    pass

        return build_architecture_prompt(
            spec_content=spec_content,
            spec_name=Path(session.spec_path).name,
            session_name=session.name,
            directories=directories,
            source_files=source_files,
            tech_stack=sorted(tech_stack),
            source_tree_str="\n".join(src_tree_lines[:80]),
            key_file_snippets=key_file_snippets,
        )

    def process_result(self, session, content, result):
        # Architecture step writes raw content without metadata header
        return content

    def _icon(self):
        return "💻"


class DevelopmentStep(PipelineStep):
    """Step 5: Claude — AI-powered development planning."""

    step_key = "development"
    agent = "Claude"
    description = "开发实现"
    output_filename = "development-plan.md"
    max_tokens = 4096

    def _artifact_keys(self):
        return ["architecture", "prd", "super-analysis"]

    def build_prompts(self, session, spec_content, parsed, artifacts):
        from pipeline.prompts import build_development_prompt
        import os
        import subprocess

        project_dir = Path(os.environ.get("OSH_HOME", ".")).resolve()

        # Gather project metrics
        git_log = ""
        git_commits = 0
        try:
            result = subprocess.run(
                ["git", "log", "--oneline", "-10", "--format=%h %s (%ar)"],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=project_dir,
            )
            if result.returncode == 0:
                git_log = result.stdout.strip()
                git_commits = (
                    len(result.stdout.strip().split("\n"))
                    if result.stdout.strip()
                    else 0
                )
        except Exception as e:
            log.warning(f"Git log failed (non-fatal): {e}")
            git_log = "(not a git repository or git not available)"

        src_lines = 0
        test_lines = 0
        src_files = (
            list(project_dir.glob("src/**/*.py"))
            + list(project_dir.glob("src/**/*.sh"))
            + list(project_dir.glob("src/**/*.html"))
        )
        test_files = list(project_dir.glob("tests/**/*.py"))

        for f in src_files:
            try:
                src_lines += len(f.read_text().splitlines())
            except Exception as e:
                log.warning("Could not read source file in count: %s", e)
                pass
        for f in test_files:
            try:
                test_lines += len(f.read_text().splitlines())
            except Exception as e:
                log.warning("Could not read test file in count: %s", e)
                pass

        return build_development_prompt(
            spec_content=spec_content,
            spec_name=Path(session.spec_path).name,
            architecture_content=artifacts.get("architecture", ""),
            prd_content=artifacts.get("prd", ""),
            super_analysis_content=artifacts.get("super-analysis", ""),
            src_lines=src_lines,
            src_file_count=len(src_files),
            test_lines=test_lines,
            test_file_count=len(test_files),
            git_commits=git_commits,
            git_log=git_log,
        )

    def _icon(self):
        return "💻"


class TestPlanningStep(PipelineStep):
    """Step 6: Claude — AI-powered test planning."""

    step_key = "test-planning"
    agent = "Claude"
    description = "测试规划"
    output_filename = "test-plan.md"
    max_tokens = 4096

    def _artifact_keys(self):
        return ["architecture", "development"]

    def build_prompts(self, session, spec_content, parsed, artifacts):
        from pipeline.prompts import build_test_planning_prompt

        requirements = parsed["requirements"]
        architecture_content = artifacts.get("architecture")
        dev_plan_content = artifacts.get("development")

        return build_test_planning_prompt(
            spec_content=spec_content,
            requirements=requirements,
            architecture_content=architecture_content,
            development_plan_content=dev_plan_content,
        )

    def _icon(self):
        return "📋"


class HermesReviewStep(PipelineStep):
    """Step 8: Hermes — AI-powered code review."""

    step_key = "code-review"
    agent = "Hermes"
    description = "代码审查"
    output_filename = "code-review.json"
    max_tokens = 4096

    def _artifact_keys(self):
        return [
            "architecture", "development", "self-test",
            "prd", "super-analysis", "review-result",
        ]

    def build_prompts(self, session, spec_content, parsed, artifacts):
        from pipeline.prompts import build_code_review_prompt
        import os

        project_dir = Path(os.environ.get("OSH_HOME", ".")).resolve()

        # Scan actual source files
        source_files: list[dict] = []
        src_dir = project_dir / "src"
        if src_dir.exists():
            for root, dirs, files in os.walk(src_dir):
                dirs[:] = [
                    d
                    for d in dirs
                    if not d.startswith(".") and d != "__pycache__"
                ]
                for f in sorted(files):
                    if f.endswith(".py"):
                        fpath = Path(root) / f
                        rel = fpath.relative_to(project_dir)
                        content = (
                            fpath.read_text()
                            if fpath.exists() and fpath.stat().st_size < 20000
                            else ""
                        )
                        source_files.append({
                            "path": str(rel),
                            "lines": len(content.splitlines()),
                            "content": content[:3000],
                        })

        return build_code_review_prompt(
            spec_content=spec_content,
            spec_name=Path(session.spec_path).name,
            session_name=session.name,
            artifact_contents=artifacts,
            source_files=source_files,
            timestamp=datetime.now().isoformat(),
        )

    def process_result(self, session, content, result):
        from pipeline.run import _try_parse_hermes_json

        raw = content.strip()
        review = _try_parse_hermes_json(raw, session.name)
        review.setdefault("session", session.name)
        review.setdefault("reviewer", "Hermes")
        review.setdefault("timestamp", datetime.now().isoformat())
        review.setdefault("status", "passed")
        review.setdefault("findings", [])
        review.setdefault(
            "finding_breakdown",
            {"critical": 0, "major": 0, "minor": 0, "info": 0},
        )
        review.setdefault("summary", "")
        return json.dumps(review, indent=2, ensure_ascii=False)

    def _icon(self):
        return "🔮"


# Map of step_key -> PipelineStep instance (singletons)
STEP_CLASSES: dict[str, PipelineStep] = {
    "super-analysis": SuperAnalysisStep(),
    "prd": PrdStep(),
    "architecture": ArchitectureStep(),
    "development": DevelopmentStep(),
    "test-planning": TestPlanningStep(),
    "code-review": HermesReviewStep(),
}


def get_step_instance(step_key: str) -> PipelineStep | None:
    """Return the singleton PipelineStep instance for *step_key*."""
    return STEP_CLASSES.get(step_key)


def register_step(step_key: str, instance: PipelineStep) -> None:
    """Register a custom step instance (for extensibility)."""
    STEP_CLASSES[step_key] = instance
