#!/usr/bin/env python3
# Copyright (c) 2025 frisky1985
# SPDX-License-Identifier: MIT

"""
yuleOSH Template Init — Create new projects from a starter spec template.

Usage:
    yuleosh template init <project-name>
    yuleosh template init <project-name> --from <template-dir>

The first form creates a generic Python project with a starter OpenSpec spec.
The second form scaffolds a project from an existing embedded template
(e.g. templates/ble-sensor, templates/can-bus, templates/mcu-firmware).

Creates:
    <project-name>/
      ├── docs/
      │   └── spec.md          — OpenSpec specification with 3+ SHALL statements
      ├── src/                  — Source code directory
      ├── tests/                — Test directory
      ├── Makefile              — Build system (for C/C++ templates)
      ├── .gitignore
      └── pyproject.toml        — Project config (Python starter only)
"""

import os
import sys
import shutil
from datetime import datetime
from pathlib import Path


STARTER_SPEC = """# {name} — OpenSpec Specification

> Generated by yuleOSH template init
> Version: 0.1.0 | Status: Draft

---

## 1. 核心功能

### Req-001: {name} 基础功能
- The system SHALL provide a configurable entry point for {name}
- The system SHALL validate input parameters before processing
- The system SHALL return structured output for downstream consumers

#### Reason
核心功能需求：确保系统有明确的入口、参数校验和结构化输出

### Req-002: 日志与监控
- The system SHALL log all operations with timestamps and severity levels
- The system SHALL support DEBUG, INFO, WARN, and ERROR log levels
- The system SHOULD expose a health check endpoint for monitoring

#### Reason
可观测性需求：日志和监控是运维和问题排查的基础

### Req-003: 错误处理
- The system SHALL return meaningful error codes for all failure modes
- The system SHALL handle unexpected exceptions without crashing the main process
- The system MAY provide retry logic for transient failures

#### Reason
健壮性需求：完善的错误处理保证系统的稳定性和可用性

---

## 2. 验收场景

### Scenario: 基本工作流
- GIVEN the system is initialized with valid configuration
- WHEN the user submits a valid request
- THEN the system SHALL process the request and return a successful response
- AND the system SHALL log the operation with INFO severity

### Scenario: 参数校验失败
- GIVEN the system is initialized
- WHEN the user submits a request with missing required parameters
- THEN the system SHALL reject the request
- AND the system SHALL return a structured error with code E001

### Scenario: 异常恢复
- GIVEN the system is processing a request
- WHEN an unexpected error occurs
- THEN the system SHALL catch the exception gracefully
- AND the system SHALL log the error with ERROR severity
- AND the system SHALL return a fallback error response
"""


PYPROJECT_TEMPLATE = """[project]
name = "{name}"
version = "0.1.0"
description = "{name} — Embedded AI development project generated by yuleOSH"
requires-python = ">=3.10"

[project.scripts]
"""

GITIGNORE_CONTENT = """__pycache__/
*.pyc
.pytest_cache/
.coverage
coverage.json
.osh/
*.egg-info/
dist/
build/
"""


def cmd_template_init(project_name: str, parent_dir: str = ".",
                      from_template: str | None = None) -> Path:
    """Initialize a new project from the yuleOSH starter template.

    Args:
        project_name: Name of the new project directory.
        parent_dir: Parent directory to create the project in.
        from_template: Optional path to a template directory to copy from.
                       If provided, the template's spec, sources, tests, and
                       Makefile are scaffolded into the new project.
    """
    project_dir = Path(parent_dir) / project_name

    if project_dir.exists():
        print(f"❌ Directory already exists: {project_dir}", file=sys.stderr)
        sys.exit(1)

    # Resolve template path relative to project root or absolute
    template_path = None
    if from_template:
        template_path = Path(from_template)
        if not template_path.is_absolute():
            # Try relative to parent_dir, then to OSH_HOME
            candidates = [
                Path(parent_dir) / from_template,
                Path(from_template),
            ]
            osh_home = os.environ.get("OSH_HOME", str(Path(__file__).resolve().parent.parent.parent))
            candidates.append(Path(osh_home) / from_template)

            for c in candidates:
                if c.exists() and c.is_dir():
                    template_path = c
                    break

        if not template_path.exists() or not template_path.is_dir():
            print(f"❌ Template directory not found: {from_template}", file=sys.stderr)
            print(f"   Checked: {template_path}", file=sys.stderr)
            sys.exit(1)

    if template_path:
        return _init_from_template(project_name, project_dir, template_path)
    else:
        return _init_starter(project_name, project_dir)


def _init_from_template(project_name: str, project_dir: Path,
                         template_path: Path) -> Path:
    """Initialize a project by copying from an existing template directory."""
    print(f"📦 Scaffolding '{project_name}' from template: {template_path}")

    # Copy all files from template to new project directory
    shutil.copytree(str(template_path), str(project_dir))

    # Remove any git state or build artifacts
    for stale in [".git", ".pytest_cache", "__pycache__", "build"]:
        stale_path = project_dir / stale
        if stale_path.exists():
            if stale_path.is_dir():
                shutil.rmtree(stale_path)
            else:
                stale_path.unlink()

    print(f"\n✅ Project '{project_name}' initialized from template at: {project_dir}")
    print(f"   Template source: {template_path}")
    print(f"   ├── docs/spec.md")
    print(f"   ├── src/")
    print(f"   ├── tests/")
    print(f"   ├── Makefile")
    print(f"   └── (template files copied)")
    print()
    print(f"   Next steps:")
    print(f"   1. Review and edit {project_dir / 'docs' / 'spec.md'}")
    print(f"   2. Run: yuleosh spec validate {project_dir / 'docs' / 'spec.md'}")
    print(f"   3. Run: yuleosh ci run 1  # Run Layer 1 CI")
    print()

    return project_dir


def _init_starter(project_name: str, project_dir: Path) -> Path:
    """Initialize a generic Python starter project."""
    # Create directory structure
    dirs = [
        project_dir / "docs",
        project_dir / "src",
        project_dir / "tests",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)

    # Write starter spec.md
    spec_content = STARTER_SPEC.format(name=project_name)
    (project_dir / "docs" / "spec.md").write_text(spec_content)

    # Write pyproject.toml
    (project_dir / "pyproject.toml").write_text(PYPROJECT_TEMPLATE.format(name=project_name))

    # Write .gitignore
    (project_dir / ".gitignore").write_text(GITIGNORE_CONTENT)

    # Create empty __init__.py for src and tests packages
    (project_dir / "src" / "__init__.py").write_text(f'""" {project_name} package."""\n')
    (project_dir / "tests" / "__init__.py").write_text("")

    # Create placeholder test
    test_content = f'''"""Tests for {project_name}."""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))


def test_placeholder():
    """Placeholder test — replace with real tests."""
    assert True
'''
    (project_dir / "tests" / f"test_{project_name}.py").write_text(test_content)

    print(f"\n✅ Project '{project_name}' initialized at: {project_dir}")
    print(f"   ├── docs/spec.md      — Starter spec with 3 requirements")
    print(f"   ├── src/               — Source code directory")
    print(f"   ├── tests/             — Test directory")
    print(f"   ├── pyproject.toml     — Project config")
    print(f"   └── .gitignore         — Ignored files")
    print()
    print(f"   Next steps:")
    print(f"   1. Edit {project_dir / 'docs' / 'spec.md'} to add your requirements")
    print(f"   2. Run: yuleosh spec validate {project_dir / 'docs' / 'spec.md'}")
    print(f"   3. Run: yuleosh ci run 1  # Run Layer 1 CI")
    print()

    return project_dir


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 template.py init <project-name> [--from <template-dir>]",
              file=sys.stderr)
        sys.exit(1)

    cmd = sys.argv[1]

    if cmd == "init":
        if len(sys.argv) < 3:
            print("Usage: python3 template.py init <project-name> [--from <template-dir>]",
                  file=sys.stderr)
            sys.exit(1)

        project_name = sys.argv[2]
        from_template = None

        # Parse optional --from flag
        if len(sys.argv) >= 5 and sys.argv[3] == "--from":
            from_template = sys.argv[4]

        cmd_template_init(project_name, from_template=from_template)
    else:
        print(f"Unknown template command: {cmd}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
