#!/usr/bin/env python3
# Copyright (c) 2025 frisky1985
# SPDX-License-Identifier: MIT

"""
Pipeline Step Base — abstract base class for pipeline step handlers.

Eliminates the ~70 lines of boilerplate duplicated across every step
handler in ``run.py`` by encapsulating the common pattern:

  1. Read spec + parse requirements/scenarios
  2. Read prior-step artifacts
  3. Build system/user prompts (subclass provides via prompts.py builders)
  4. Call LLM with retry/timeout (handled by base)
  5. Parse & log usage metadata
  6. Write output file
  7. Return output path
  8. Wrap exceptions as PipelineStepError

Usage::

    class MyStep(PipelineStep):
        step_key = "my-step"
        agent = "Claude"
        description = "My custom step"
        output_filename = "my-step.md"

        def build_prompts(self, session, spec_content, parsed, artifacts):
            from yuleosh.pipeline.prompts import build_xxx_prompt
            return build_xxx_prompt(...)

"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from yuleosh.pipeline.session import PipelineSession, PipelineStepError
from yuleosh.pipeline.stages import _call_llm, _parse_spec

log = logging.getLogger("pipeline.steps")


class PipelineStep:
    """Abstract base for a single pipeline step.

    Subclasses override :meth:`build_prompts` and set class-level
    metadata.  The base class handles LLM invocation, token logging,
    file writing, and error wrapping.
    """

    # ---- Override in subclass -------------------------------------------
    step_key: str = ""
    agent: str = ""
    description: str = ""
    output_filename: str = ""
    # Set to True when the step does NOT call the LLM
    no_llm: bool = False

    # Optional max_tokens override (None = use LLM default)
    max_tokens: Optional[int] = None

    def build_prompts(
        self,
        session: PipelineSession,
        spec_content: str,
        parsed: dict,
        artifacts: dict[str, str],
    ) -> tuple[str, str]:
        """Return ``(system_prompt, user_prompt)``.

        Called by the base class after the spec has been read and
        parsed.  ``artifacts`` maps prior-step keys to their on-disk
        content (already read from the file).
        """
        raise NotImplementedError

    def process_result(
        self,
        session: PipelineSession,
        content: str,
        result: dict,
    ) -> str:
        """Post-process LLM output before writing to file.

        The default implementation prepends a metadata header.
        Override to transform the output (e.g. JSON parsing for
        review steps).  Return the final string to write.
        """
        usage = result.get("usage", {})
        parsed = _parse_spec(session.spec_path)
        requirements = parsed["requirements"]
        scenarios = parsed["scenarios"]
        total_shall = sum(len(r.get("shall_statements", [])) for r in requirements)

        header = (
            f"# {self.description}: {Path(session.spec_path).stem}\n\n"
            f"> Source spec: {session.spec_path}\n"
            f"> Generated by: LLM ({result.get('model', 'unknown')})\n"
            f"> Requirements: {len(requirements)}  |  "
            f"SHALLs: {total_shall}  |  "
            f"Scenarios: {len(scenarios)}\n"
            f"> Tokens: {usage.get('total_tokens', '?')} "
            f"(prompt {usage.get('prompt_tokens', '?')} + "
            f"completion {usage.get('completion_tokens', '?')})\n\n"
        )
        return header + content

    # ---- Template method -------------------------------------------------

    def _read_artifacts(
        self, session: PipelineSession, keys: list[str]
    ) -> dict[str, str]:
        """Read the content of prior-step artifacts from disk."""
        contents: dict[str, str] = {}
        for key in keys:
            if key in session.artifacts:
                p = Path(session.artifacts[key])
                if p.exists():
                    contents[key] = p.read_text()
        return contents

    def __call__(self, session: PipelineSession) -> str:
        """Execute the step (called by the pipeline orchestrator)."""
        import time as _time

        _t0 = _time.perf_counter()
        try:
            log.info("Running %s: %s", self.agent, self.description)
            print(f"  {self._icon()} [{self.agent}] {self.description}...")

            # --- Read spec ---
            spec_path = Path(session.spec_path)
            spec_content = (
                spec_path.read_text()
                if spec_path.exists()
                else "(spec file not found)"
            )
            parsed = _parse_spec(session.spec_path)

            # --- Read prior-step artifact content ---
            artifact_keys = self._artifact_keys()
            artifacts = self._read_artifacts(session, artifact_keys)

            # --- Build prompts & call LLM (or skip for non-LLM steps) ---
            if self.no_llm:
                result = self._run_without_llm(
                    session, spec_content, parsed, artifacts
                )
            else:
                system_prompt, user_prompt = self.build_prompts(
                    session, spec_content, parsed, artifacts
                )
                kwargs = {}
                if self.max_tokens is not None:
                    kwargs["max_tokens"] = self.max_tokens
                try:
                    result = _call_llm(session, system_prompt, user_prompt, **kwargs)
                except Exception as e:
                    log.error("LLM call failed during %s: %s", self.step_key, e)
                    raise PipelineStepError(
                        f"{self.description} LLM call failed: {e}\n"
                        f"Spec: {session.spec_path}"
                    )

                content = result["content"]
                usage = result.get("usage", {})
                log.info(
                    "LLM returned %d tokens (prompt=%s, completion=%s) [%s]",
                    usage.get("total_tokens", "?"),
                    usage.get("prompt_tokens", "?"),
                    usage.get("completion_tokens", "?"),
                    self.step_key,
                )

                # Accumulate token usage on session
                if hasattr(session, "token_usage_total"):
                    session.token_usage_total += usage.get("total_tokens", 0)
                    session.token_usage_steps.append({
                        "step": self.step_key,
                        "usage": usage,
                    })

                # --- Post-process & write ---
                full_output = self.process_result(session, content, result)

            out_path = session.session_dir / self.output_filename
            try:
                out_path.write_text(
                    result if self.no_llm else full_output
                )
            except OSError as e:
                log.error("Cannot write %s: %s", self.output_filename, e)
                raise PipelineStepError(
                    f"Cannot write {self.output_filename}: {e}"
                )

            print(
                f"  ✅ [{self.agent}] {self.description} "
                f"generated at {out_path}"
            )
            _elapsed = _time.perf_counter() - _t0
            log.info("%s saved to %s (%.3fs)", self.step_key, out_path, _elapsed)
            return str(out_path)

        except PipelineStepError:
            _elapsed = _time.perf_counter() - _t0
            log.info("Step %s FAILED after %.3fs", self.step_key, _elapsed)
            raise
        except Exception as e:
            _elapsed = _time.perf_counter() - _t0
            log.error("%s failed after %.3fs: %s", self.step_key, _elapsed, e)
            raise PipelineStepError(f"{self.description} failed: {e}")

    # ---- Hooks for subclasses --------------------------------------------

    def _icon(self) -> str:
        """Return the emoji icon for this step."""
        return "🔄"

    def _artifact_keys(self) -> list[str]:
        """Return keys of prior-step artifacts to read.

        The base class returns an empty list.  Override in steps that
        depend on earlier outputs.
        """
        return []

    def _run_without_llm(
        self,
        session: PipelineSession,
        spec_content: str,
        parsed: dict,
        artifacts: dict[str, str],
    ) -> str:
        """Called when ``no_llm = True``.

        Return the content to write to the output file.
        """
        raise NotImplementedError


# ---------------------------------------------------------------------------
# Concrete step implementations
# ---------------------------------------------------------------------------

