"""
yuleOSH AI Preview — Pipeline config recommender.

Provides ``_recommend_template()`` which suggests a pipeline template
based on detected frameworks, complexity, and risk findings.
"""


def _recommend_template(frameworks: list, complexity: dict, risks: list) -> dict:
    """Recommend a pipeline template based on analysis (PREVIEW-REQ-004.3)."""
    framework_names = [f["name"] for f in frameworks]

    # Determine best template match
    if "FreeRTOS" in framework_names:
        recommended = "freertos-misra"
    elif "Zephyr" in framework_names:
        recommended = "zephyr-rtos"
    elif "AUTOSAR" in framework_names:
        recommended = "autosar-classic"
    elif "STM32 HAL" in framework_names:
        recommended = "stm32-hal"
    elif "ESP-IDF" in framework_names:
        recommended = "esp32-idf"
    elif "ARM CMSIS" in framework_names:
        recommended = "arm-cmsis"
    elif "Linux Kernel" in framework_names:
        recommended = "generic-embedded-c"
    else:
        recommended = "generic-embedded-c"

    # Build recommended steps
    steps = [
        {"name": "Spec Parsing", "rationale": "Parse and validate OpenSpec"},
        {"name": "Requirements Analysis", "rationale": "Analyze requirements and traceability"},
        {"name": "System Design Document", "rationale": "Generate architecture document"},
        {"name": "Code Generation", "rationale": "AI-assisted code generation"},
        {"name": "Internal Review", "rationale": "Quality gate before external review"},
        {"name": "Test Plan Generation", "rationale": "Generate test cases from spec"},
        {"name": "Code Review (4-Agent Matrix)", "rationale": "Multi-agent review for quality, security, style, safety"},
    ]

    # Adjust based on analysis
    if framework_names:
        steps.append({"name": "Cross-Compile + Static Analysis", "rationale": f"Target platform: {framework_names[0]}"})

    # Safety-critical: add extra gates
    has_dynamic_memory = any("Dynamic memory" in str(r) for r in risks)
    has_recursion = any("Recursive" in str(r) for r in risks)
    if has_dynamic_memory or has_recursion or complexity.get("max_function_lines", 0) > 100:
        steps.append({"name": "MISRA Static Analysis", "rationale": "Safety-critical: enforce MISRA-C rules"})
        steps.append({"name": "Safety Review", "rationale": "ISO 26262 compliance review"})

    steps.append({"name": "System Verification + Evidence Pack", "rationale": "Final verification and traceability evidence"})

    # Generate YAML snippet
    yaml_snippet = f"""# Recommended pipeline config for {recommended}
# Generated by yuleOSH AI Preview Assessment
steps:
"""
    for s in steps:
        yaml_snippet += f"""  - id: {s['name'].lower().replace(' ', '-')}
    name: {s['name']}
    handler: auto
"""
    yaml_snippet += """
ci_layers:
  L1:
    unit_test: true
    linter: true
  L2:
    cross_compile: true
    static_analysis: true
"""

    return {
        "recommended_template": recommended,
        "steps": steps,
        "ci_layers": {
            "L1": {"unit_test": True, "linter": True},
            "L2": {"cross_compile": True, "static_analysis": True},
        },
        "review_gates": [
            {"type": "internal", "before": "code-gen"},
            {"type": "compliance", "after": "system-verification"},
        ],
        "yaml_snippet": yaml_snippet,
    }
