apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "yuleosh.fullname" . }}-data
  labels:
    {{- include "yuleosh.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
